language: elixir
elixir:
  - 1.0.4
otp_release:
  - 17.5
notifications:
  email:
    recipients:
      - a@zencoder.com
before_script:
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
